name: CI (Lint)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - uses: pre-commit/action@v3.0.1
