name: "Commit Message Check"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  check-commit-message:
    uses: Slicer/Slicer/.github/workflows/commit-message.yml@418027bc07ce0aff12fe97c0e769062cc090a961 # main
